### ISSUE TITLE
Active Directory integration

### ISSUE THREAD

**Issue by klmj** [raiym/knox-knowledge-base#1]
Hello,
First of all, thank you for sharing your tips, greatly appreciate it !

I was wondering if you tried to sync more than just users from AD, thanks to your guide we managed to get to that point. But now we want to go further, and I would like to find a way to sync Organization membership for our users. Did you know a way to accomplish it ?

Until now, we tried to :
- sync AD Groups as Organization in KM : members not binded to Org in KM
- sync AD Groups as Groups in KM with Organization's attribute set on AD Groups : group members not binded to Org in KM
- sync AD Users from synced AD Groups, with Organization's attribute set on AD Users : users not binded to Org in KM
- sync AD Users/AD Groups with Organisation fixed : users/members not binded to Org in KM

Regards

PS : sorry for creating an issue not directly related to your KB, but I don't now how to contact you directly on GitHub.

**Comment by raiym** [comment]
@klmj good day! 
Surprised that after more than 2 years this tutorial is still not obsolete. 
I am not working at Samsung anymore so can't help much with Knox Manage. 
The fastest way to get help is to signup and raise a ticket on samsungknox.com (sign in required), regional B2B team will contact you, I believe, very soon.
